run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - prealloc

issues:
  exclude-dirs:
    - gen
